/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as ServicesTechnologyRouteImport } from './routes/services.technology'
import { Route as ServicesRpoRouteImport } from './routes/services.rpo'
import { Route as ServicesPermanentHiringRouteImport } from './routes/services.permanent-hiring'
import { Route as ServicesGccRouteImport } from './routes/services.gcc'
import { Route as ServicesExecutiveSearchRouteImport } from './routes/services.executive-search'
import { Route as ServicesContractStaffingRouteImport } from './routes/services.contract-staffing'
import { Route as ServicesAiTalentRouteImport } from './routes/services.ai-talent'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTechnologyRoute = ServicesTechnologyRouteImport.update({
  id: '/services/technology',
  path: '/services/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRpoRoute = ServicesRpoRouteImport.update({
  id: '/services/rpo',
  path: '/services/rpo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPermanentHiringRoute = ServicesPermanentHiringRouteImport.update({
  id: '/services/permanent-hiring',
  path: '/services/permanent-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGccRoute = ServicesGccRouteImport.update({
  id: '/services/gcc',
  path: '/services/gcc',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExecutiveSearchRoute = ServicesExecutiveSearchRouteImport.update({
  id: '/services/executive-search',
  path: '/services/executive-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContractStaffingRoute =
  ServicesContractStaffingRouteImport.update({
    id: '/services/contract-staffing',
    path: '/services/contract-staffing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiTalentRoute = ServicesAiTalentRouteImport.update({
  id: '/services/ai-talent',
  path: '/services/ai-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-talent': typeof ServicesAiTalentRoute
  '/services/contract-staffing': typeof ServicesContractStaffingRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/gcc': typeof ServicesGccRoute
  '/services/permanent-hiring': typeof ServicesPermanentHiringRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-talent': typeof ServicesAiTalentRoute
  '/services/contract-staffing': typeof ServicesContractStaffingRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/gcc': typeof ServicesGccRoute
  '/services/permanent-hiring': typeof ServicesPermanentHiringRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/careers': typeof CareersIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-talent': typeof ServicesAiTalentRoute
  '/services/contract-staffing': typeof ServicesContractStaffingRoute
  '/services/executive-search': typeof ServicesExecutiveSearchRoute
  '/services/gcc': typeof ServicesGccRoute
  '/services/permanent-hiring': typeof ServicesPermanentHiringRoute
  '/services/rpo': typeof ServicesRpoRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/insights/$slug'
    | '/services/ai-talent'
    | '/services/contract-staffing'
    | '/services/executive-search'
    | '/services/gcc'
    | '/services/permanent-hiring'
    | '/services/rpo'
    | '/services/technology'
    | '/careers/'
    | '/case-studies/'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/insights/$slug'
    | '/services/ai-talent'
    | '/services/contract-staffing'
    | '/services/executive-search'
    | '/services/gcc'
    | '/services/permanent-hiring'
    | '/services/rpo'
    | '/services/technology'
    | '/careers'
    | '/case-studies'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/insights/$slug'
    | '/services/ai-talent'
    | '/services/contract-staffing'
    | '/services/executive-search'
    | '/services/gcc'
    | '/services/permanent-hiring'
    | '/services/rpo'
    | '/services/technology'
    | '/careers/'
    | '/case-studies/'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersSlugRoute: typeof CareersSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ServicesAiTalentRoute: typeof ServicesAiTalentRoute
  ServicesContractStaffingRoute: typeof ServicesContractStaffingRoute
  ServicesExecutiveSearchRoute: typeof ServicesExecutiveSearchRoute
  ServicesGccRoute: typeof ServicesGccRoute
  ServicesPermanentHiringRoute: typeof ServicesPermanentHiringRoute
  ServicesRpoRoute: typeof ServicesRpoRoute
  ServicesTechnologyRoute: typeof ServicesTechnologyRoute
  CareersIndexRoute: typeof CareersIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/technology': {
      id: '/services/technology'
      path: '/services/technology'
      fullPath: '/services/technology'
      preLoaderRoute: typeof ServicesTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rpo': {
      id: '/services/rpo'
      path: '/services/rpo'
      fullPath: '/services/rpo'
      preLoaderRoute: typeof ServicesRpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/permanent-hiring': {
      id: '/services/permanent-hiring'
      path: '/services/permanent-hiring'
      fullPath: '/services/permanent-hiring'
      preLoaderRoute: typeof ServicesPermanentHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gcc': {
      id: '/services/gcc'
      path: '/services/gcc'
      fullPath: '/services/gcc'
      preLoaderRoute: typeof ServicesGccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/executive-search': {
      id: '/services/executive-search'
      path: '/services/executive-search'
      fullPath: '/services/executive-search'
      preLoaderRoute: typeof ServicesExecutiveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/contract-staffing': {
      id: '/services/contract-staffing'
      path: '/services/contract-staffing'
      fullPath: '/services/contract-staffing'
      preLoaderRoute: typeof ServicesContractStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-talent': {
      id: '/services/ai-talent'
      path: '/services/ai-talent'
      fullPath: '/services/ai-talent'
      preLoaderRoute: typeof ServicesAiTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersSlugRoute: CareersSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ServicesAiTalentRoute: ServicesAiTalentRoute,
  ServicesContractStaffingRoute: ServicesContractStaffingRoute,
  ServicesExecutiveSearchRoute: ServicesExecutiveSearchRoute,
  ServicesGccRoute: ServicesGccRoute,
  ServicesPermanentHiringRoute: ServicesPermanentHiringRoute,
  ServicesRpoRoute: ServicesRpoRoute,
  ServicesTechnologyRoute: ServicesTechnologyRoute,
  CareersIndexRoute: CareersIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
